In [26]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from prophet import Prophet

# Configuração visual padrão para os gráficos do curso
sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

print("Ambiente 100% configurado e pronto para o curso!")

Ambiente 100% configurado e pronto para o curso!

In [27]:
# Carrega a base de dados configurando a coluna de tempo corretamente
df = pd.read_csv('Dados/bicicletas.csv')

# Exibe as 5 primeiras linhas para analisarmos a estrutura
df.head()

,data_hora,contagem,temperatura,sensacao_termica,umidade,velocidade_vento,clima,feriado,fim_de_semana,estacao
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,Nublado,Não,Sim,Inverno
1,2015-01-04 01:00:00,138,NaN,NaN,93.0,5.0,Céu limpo,Não,Sim,Inverno
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,Céu limpo,Não,Sim,Inverno
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,Céu limpo,Não,Sim,Inverno
4,2015-01-04 04:00:00,47,NaN,NaN,93.0,6.5,Céu limpo,Não,Sim,Inverno

![Pipeline de Ciência de Dados](img/graf1.jpg)

## 🔄 Etapas do Ciclo de Desenvolvimento

O projeto segue as 6 fases metodológicas do pipeline de Ciência de Dados para garantir uma entrega orientada a resultados:

### 1. Identificação
Foco no entendimento profundo do problema de negócio e alinhamento de expectativas.
* **Mapeamento:** Definição clara do objetivo final e do público-alvo do projeto.
* **Restrições:** Levantamento de limitações técnicas e mapeamento de dados disponíveis.
* **Entrega:** Contextualização robusta do problema e desenho da hipótese de solução.

### 2. Preparação
Fase dedicada à coleta inicial e ao diagnóstico estrutural da base de dados.
* **Auditoria:** Identificação de falhas, inconsistências e lacunas no conjunto de dados.
* **Planejamento:** Formulação das estratégias de análise com base nos tipos de variáveis.
* **Entrega:** Compreensão detalhada do potencial e das limitações das tabelas disponíveis.

### 3. Processamento
Execução da limpeza e transformação dos dados para elevar a qualidade do pipeline.
* **Tratamento:** Resolução de dados ausentes (*NaN*) e remoção de registros duplicados.
* **Tipagem:** Conversão de formatos de colunas (como transformação de textos para *datetime*).
* **Entrega:** Uma base de dados higienizada, consistente e pronta para modelagem.

### 4. Análise
Exploração estatística dos dados tratados em busca de insights acionáveis.
* **Mineração:** Descoberta de padrões ocultos, tendências temporais e anomalias.
* **Correlação:** Identificação de relações matemáticas e dependências entre as variáveis.
* **Entrega:** Descobertas relevantes ligadas diretamente ao comportamento de consumo.

### 5. Modelagem
Construção, treinamento e otimização dos algoritmos preditivos.
* **Validação:** Testes de hipóteses estatísticas para validar as premissas da análise.
* **Predição:** Desenvolvimento do modelo matemático focado em prever novos valores.
* **Ajuste:** Mensuração de desempenho e tunagem para otimização dos resultados.

### 6. Compartilhamento
Fase final de comunicação dos resultados e tradução técnica para o negócio.
* **Visualização:** Construção de gráficos claros, relatórios ou apresentações executivas.
* **Critérios:** Adaptação da mensagem de acordo com o público-alvo do projeto.
* **Entrega:** Solução prática e provada, gerando valor real para a tomada de decisão.

![Gráfico 2 - Análise](img/graf2.jpg)

In [28]:
df.head()

,data_hora,contagem,temperatura,sensacao_termica,umidade,velocidade_vento,clima,feriado,fim_de_semana,estacao
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,Nublado,Não,Sim,Inverno
1,2015-01-04 01:00:00,138,NaN,NaN,93.0,5.0,Céu limpo,Não,Sim,Inverno
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,Céu limpo,Não,Sim,Inverno
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,Céu limpo,Não,Sim,Inverno
4,2015-01-04 04:00:00,47,NaN,NaN,93.0,6.5,Céu limpo,Não,Sim,Inverno

In [29]:
# Retorna a quantidade de linhas e colunas do DataFrame
dados.shape

(17429, 10)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17429 entries, 0 to 17428
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_hora         17429 non-null  str
 1   contagem          17429 non-null  int64
 2   temperatura       17406 non-null  float64
 3   sensacao_termica  17406 non-null  float64
 4   umidade           17429 non-null  float64
 5   velocidade_vento  17429 non-null  float64
 6   clima             17429 non-null  str
 7   feriado           17429 non-null  str
 8   fim_de_semana     17429 non-null  str
 9   estacao           17429 non-null  str
dtypes: float64(4), int64(1), str(5)
memory usage: 1.3 MB

In [31]:
# Verifica a quantidade de valores nulos (ausentes) em cada coluna
dados.isnull().sum()

data_hora           0
contagem            0
temperatura         0
sensacao_termica    0
umidade             0
velocidade_vento    0
clima               0
feriado             0
fim_de_semana       0
estacao             0
dtype: int64

In [32]:
# Preenche os valores ausentes de temperatura por interpolação linear
df['temperatura'] = df['temperatura'].interpolate(method='linear')
df['sensacao_termica'] = df['sensacao_termica'].interpolate(method='linear')

In [33]:
df.head(10)

,data_hora,contagem,temperatura,sensacao_termica,umidade,velocidade_vento,clima,feriado,fim_de_semana,estacao
0,2015-01-04 00:00:00,182,3.00,2.00,93.0,6.0,Nublado,Não,Sim,Inverno
1,2015-01-04 01:00:00,138,2.75,2.25,93.0,5.0,Céu limpo,Não,Sim,Inverno
2,2015-01-04 02:00:00,134,2.50,2.50,96.5,0.0,Céu limpo,Não,Sim,Inverno
3,2015-01-04 03:00:00,72,2.00,2.00,100.0,0.0,Céu limpo,Não,Sim,Inverno
4,2015-01-04 04:00:00,47,2.00,2.00,93.0,6.5,Céu limpo,Não,Sim,Inverno
5,2015-01-04 05:00:00,46,2.00,2.00,93.0,4.0,Céu limpo,Não,Sim,Inverno
6,2015-01-04 06:00:00,51,1.00,-1.00,100.0,7.0,Parcialmente nublado,Não,Sim,Inverno
7,2015-01-04 07:00:00,75,1.00,-1.00,100.0,7.0,Parcialmente nublado,Não,Sim,Inverno
8,2015-01-04 08:00:00,131,1.50,-1.00,96.5,8.0,Parcialmente nublado,Não,Sim,Inverno
9,2015-01-04 09:00:00,301,2.00,-0.50,100.0,9.0,Nublado,Não,Sim,Inverno

In [35]:
# Retorna a quantidade total de linhas duplicadas no DataFrame
df.duplicated().sum()

np.int64(15)

In [36]:
# Identifica todas as ocorrências de linhas duplicadas, marcando todas como True
df.duplicated(keep=False)

0        False
1        False
2        False
3        False
4        False
         ...
17424     True
17425     True
17426     True
17427     True
17428     True
Length: 17429, dtype: bool

In [37]:
# Armazena em uma variável uma máscara booleana que identifica todas as linhas duplicadas
duplicatas = df.duplicated(keep=False)

In [38]:
# Filtra o DataFrame original e armazena os registros repetidos em uma nova variável
linhas_duplicadas = df[duplicatas]

# Exibe na tela a tabela contendo apenas as linhas duplicadas encontradas
linhas_duplicadas

,data_hora,contagem,temperatura,sensacao_termica,umidade,velocidade_vento,clima,feriado,fim_de_semana,estacao
519,2015-01-25 16:00:00,1238,8.0,5.0,71.0,18.0,Nublado,Não,Sim,Inverno
869,2015-02-09 06:00:00,479,5.0,3.5,87.0,6.5,Parcialmente nublado,Não,Não,Inverno
3655,2015-06-05 18:00:00,3411,23.0,23.0,50.0,26.0,Parcialmente nublado,Não,Não,Verão
4167,2015-06-27 02:00:00,337,15.5,15.5,74.5,18.0,Parcialmente nublado,Não,Sim,Verão
4658,2015-07-17 14:00:00,1882,24.5,24.5,44.0,29.5,Parcialmente nublado,Não,Não,Verão
5360,2015-08-15 23:00:00,759,17.0,17.0,59.0,6.0,Céu limpo,Não,Sim,Verão
8174,2015-12-12 11:00:00,1100,12.0,12.0,82.0,20.0,Chuva leve,Não,Sim,Inverno
8175,2015-12-12 12:00:00,1308,13.0,13.0,77.0,26.0,Chuva leve,Não,Sim,Inverno
8528,2015-12-27 05:00:00,57,15.0,15.0,72.0,31.0,Parcialmente nublado,Não,Sim,Inverno
9428,2016-02-02 17:00:00,2846,8.0,4.5,59.5,23.0,Parcialmente nublado,Não,Não,Inverno
11646,2016-05-06 03:00:00,77,9.5,9.0,79.0,6.0,Céu limpo,Não,Não,Primavera
12350,2016-06-04 11:00:00,1779,15.5,15.5,85.5,8.0,Nublado,Não,Sim,Verão
12443,2016-06-08 08:00:00,4672,18.0,18.0,83.0,2.0,Céu limpo,Não,Não,Verão
16848,2016-12-11 10:00:00,1098,7.5,4.5,87.0,16.0,Céu limpo,Não,Sim,Inverno
17128,2016-12-23 02:00:00,92,7.5,5.5,90.0,10.0,Céu limpo,Não,Não,Inverno
17414,2016-05-06 03:00:00,77,9.5,9.0,79.0,6.0,Céu limpo,Não,Não,Primavera
17415,2015-12-27 05:00:00,57,15.0,15.0,72.0,31.0,Parcialmente nublado,Não,Sim,Inverno
17416,2016-06-08 08:00:00,4672,18.0,18.0,83.0,2.0,Céu limpo,Não,Não,Verão
17417,2015-02-09 06:00:00,479,5.0,3.5,87.0,6.5,Parcialmente nublado,Não,Não,Inverno
17418,2015-07-17 14:00:00,1882,24.5,24.5,44.0,29.5,Parcialmente nublado,Não,Não,Verão
17419,2016-06-04 11:00:00,1779,15.5,15.5,85.5,8.0,Nublado,Não,Sim,Verão
17420,2015-12-12 12:00:00,1308,13.0,13.0,77.0,26.0,Chuva leve,Não,Sim,Inverno
17421,2015-06-27 02:00:00,337,15.5,15.5,74.5,18.0,Parcialmente nublado,Não,Sim,Verão
17422,2015-01-25 16:00:00,1238,8.0,5.0,71.0,18.0,Nublado,Não,Sim,Inverno
17423,2016-12-23 02:00:00,92,7.5,5.5,90.0,10.0,Céu limpo,Não,Não,Inverno
17424,2016-12-11 10:00:00,1098,7.5,4.5,87.0,16.0,Céu limpo,Não,Sim,Inverno
17425,2015-06-05 18:00:00,3411,23.0,23.0,50.0,26.0,Parcialmente nublado,Não,Não,Verão
17426,2015-12-12 11:00:00,1100,12.0,12.0,82.0,20.0,Chuva leve,Não,Sim,Inverno
17427,2016-02-02 17:00:00,2846,8.0,4.5,59.5,23.0,Parcialmente nublado,Não,Não,Inverno
17428,2015-08-15 23:00:00,759,17.0,17.0,59.0,6.0,Céu limpo,Não,Sim,Verão

In [39]:
# Ordena o DataFrame de registros repetidos cronologicamente pela coluna de tempo
linhas_duplicadas.sort_values(by='data_hora')

,data_hora,contagem,temperatura,sensacao_termica,umidade,velocidade_vento,clima,feriado,fim_de_semana,estacao
519,2015-01-25 16:00:00,1238,8.0,5.0,71.0,18.0,Nublado,Não,Sim,Inverno
17422,2015-01-25 16:00:00,1238,8.0,5.0,71.0,18.0,Nublado,Não,Sim,Inverno
869,2015-02-09 06:00:00,479,5.0,3.5,87.0,6.5,Parcialmente nublado,Não,Não,Inverno
17417,2015-02-09 06:00:00,479,5.0,3.5,87.0,6.5,Parcialmente nublado,Não,Não,Inverno
3655,2015-06-05 18:00:00,3411,23.0,23.0,50.0,26.0,Parcialmente nublado,Não,Não,Verão
17425,2015-06-05 18:00:00,3411,23.0,23.0,50.0,26.0,Parcialmente nublado,Não,Não,Verão
4167,2015-06-27 02:00:00,337,15.5,15.5,74.5,18.0,Parcialmente nublado,Não,Sim,Verão
17421,2015-06-27 02:00:00,337,15.5,15.5,74.5,18.0,Parcialmente nublado,Não,Sim,Verão
4658,2015-07-17 14:00:00,1882,24.5,24.5,44.0,29.5,Parcialmente nublado,Não,Não,Verão
17418,2015-07-17 14:00:00,1882,24.5,24.5,44.0,29.5,Parcialmente nublado,Não,Não,Verão
17428,2015-08-15 23:00:00,759,17.0,17.0,59.0,6.0,Céu limpo,Não,Sim,Verão
5360,2015-08-15 23:00:00,759,17.0,17.0,59.0,6.0,Céu limpo,Não,Sim,Verão
17426,2015-12-12 11:00:00,1100,12.0,12.0,82.0,20.0,Chuva leve,Não,Sim,Inverno
8174,2015-12-12 11:00:00,1100,12.0,12.0,82.0,20.0,Chuva leve,Não,Sim,Inverno
17420,2015-12-12 12:00:00,1308,13.0,13.0,77.0,26.0,Chuva leve,Não,Sim,Inverno
8175,2015-12-12 12:00:00,1308,13.0,13.0,77.0,26.0,Chuva leve,Não,Sim,Inverno
17415,2015-12-27 05:00:00,57,15.0,15.0,72.0,31.0,Parcialmente nublado,Não,Sim,Inverno
8528,2015-12-27 05:00:00,57,15.0,15.0,72.0,31.0,Parcialmente nublado,Não,Sim,Inverno
17427,2016-02-02 17:00:00,2846,8.0,4.5,59.5,23.0,Parcialmente nublado,Não,Não,Inverno
9428,2016-02-02 17:00:00,2846,8.0,4.5,59.5,23.0,Parcialmente nublado,Não,Não,Inverno
17414,2016-05-06 03:00:00,77,9.5,9.0,79.0,6.0,Céu limpo,Não,Não,Primavera
11646,2016-05-06 03:00:00,77,9.5,9.0,79.0,6.0,Céu limpo,Não,Não,Primavera
12350,2016-06-04 11:00:00,1779,15.5,15.5,85.5,8.0,Nublado,Não,Sim,Verão
17419,2016-06-04 11:00:00,1779,15.5,15.5,85.5,8.0,Nublado,Não,Sim,Verão
12443,2016-06-08 08:00:00,4672,18.0,18.0,83.0,2.0,Céu limpo,Não,Não,Verão
17416,2016-06-08 08:00:00,4672,18.0,18.0,83.0,2.0,Céu limpo,Não,Não,Verão
17424,2016-12-11 10:00:00,1098,7.5,4.5,87.0,16.0,Céu limpo,Não,Sim,Inverno
16848,2016-12-11 10:00:00,1098,7.5,4.5,87.0,16.0,Céu limpo,Não,Sim,Inverno
17423,2016-12-23 02:00:00,92,7.5,5.5,90.0,10.0,Céu limpo,Não,Não,Inverno
17128,2016-12-23 02:00:00,92,7.5,5.5,90.0,10.0,Céu limpo,Não,Não,Inverno